**Load in Numpy**

In [1]:
import numpy as np
import sys

**The Basics**

In [12]:
a = np.array([1,2,3], dtype='int16')
b = np.array ([[1.0,2.8,3.3],[4,5.8,6.0]])
print (b)

[[1.  2.8 3.3]
 [4.  5.8 6. ]]


In [8]:
b.ndim # dimension

2

In [9]:
b.shape #shape

(2, 3)

In [14]:
a.dtyp #size

dtype('int16')

In [15]:
a.itemsize

2

In [16]:
a.nbytes

6

In [17]:
b.nbytes

48

**Accessing/Changing specific elements,rows,columns etc.**

In [24]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
#Getting in to the specific element
a[1,5]

13

In [29]:
a[0,4]

5

In [ ]:
# Specific row

In [31]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [32]:
a[:,2]

array([ 3, 10])

array([ 8,  9, 10, 11, 12, 13, 14])

In [37]:
a[1, 1:6:2]

array([ 9, 11, 13])

In [39]:
# Change
a[1,2] = 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 20 11 12 20 14]]


In [45]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [46]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
b.shape

(2, 2, 2)

In [49]:
# Element
b[0,0,1]

2

In [50]:
b[1,1,0]

7

In [51]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [52]:
b[1,:,:]

array([[5, 6],
       [7, 8]])

In [53]:
b[:,:,1]

array([[2, 4],
       [6, 8]])