**Load in Numpy**

In [1]:
import numpy as np
import sys

**The Basics**

In [12]:
a = np.array([1,2,3], dtype='int16')
b = np.array ([[1.0,2.8,3.3],[4,5.8,6.0]])
print (b)

[[1.  2.8 3.3]
 [4.  5.8 6. ]]


In [8]:
b.ndim # dimension

2

In [9]:
b.shape #shape

(2, 3)

In [14]:
a.dtyp #size

dtype('int16')

In [15]:
a.itemsize

2

In [16]:
a.nbytes

6

In [17]:
b.nbytes

48

**Accessing/Changing specific elements,rows,columns etc.**

In [24]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
#Getting in to the specific element
a[1,5]

13

In [29]:
a[0,4]

5

In [ ]:
# Specific row

In [31]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [32]:
a[:,2]

array([ 3, 10])

array([ 8,  9, 10, 11, 12, 13, 14])

In [37]:
a[1, 1:6:2]

array([ 9, 11, 13])

In [39]:
# Change
a[1,2] = 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 20 11 12 20 14]]


In [45]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [46]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
b.shape

(2, 2, 2)

In [49]:
# Element
b[0,0,1]

2

In [50]:
b[1,1,0]

7

In [51]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [52]:
b[1,:,:]

array([[5, 6],
       [7, 8]])

In [53]:
b[:,:,1]

array([[2, 4],
       [6, 8]])

**Initializing Different Types of Arrays**

In [69]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [65]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [70]:
np.full((2,2,2), 7, dtype="float32") #other numbers in float

array([[[7., 7.],
        [7., 7.]],

       [[7., 7.],
        [7., 7.]]], dtype=float32)

In [71]:
np.full(a.shape,4) #Using the other shape for(shape of a)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [74]:
np.random.rand(4,2,3)

array([[[0.64416323, 0.88577639, 0.60316342],
        [0.28789281, 0.68273935, 0.08509948]],

       [[0.3591779 , 0.61073236, 0.11832376],
        [0.49512211, 0.62495965, 0.38405579]],

       [[0.97600218, 0.75973845, 0.83117858],
        [0.91022095, 0.503958  , 0.58483946]],

       [[0.04864438, 0.6804783 , 0.20935308],
        [0.97939838, 0.82493945, 0.72512658]]])

In [86]:
np.random.randint((3,4))

array([2, 1])

In [87]:
np.random.randint(10, size=(3,4))

array([[6, 0, 8, 7],
       [6, 8, 9, 9],
       [8, 1, 8, 2]])

In [92]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
arr=np.array([[1,2,3,4,5]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [109]:
d=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
d[1:4,1:4]=z
print(d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [108]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

**Math**

In [110]:
a=np.array([1,2,3,4,5])

In [111]:
a + 2

array([3, 4, 5, 6, 7])

In [112]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [113]:
a+=2
a

array([3, 4, 5, 6, 7])

In [114]:
b = np.array((1,2,3,4,5))
a+b

array([ 4,  6,  8, 10, 12])

In [115]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

## Linear Algebra

In [116]:
a=np.ones((2,3))
print (a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [119]:
b=np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [120]:
np.matmul(a,b) #multiplication

array([[6., 6.],
       [6., 6.]])

In [122]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
np.linalg.det(c)

1.0

NameError: name 'stars' is not defined